config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  # resources :profiles, only: [:index]

    get 'follower', to: 'profiles#follower'
    
    get 'alluser', to: 'profiles#alluser'

    resources :users, only: [:show] do
    	resources :followings, only: [:create, :destroy]
    end


    get 'leader', to: 'profiles#leader'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 	root to: "tweets#index"
  	
  	resources :tweets do
  		resources :replies, only: [:create, :edit, :update, :destroy]
  		resources :likes, only: [:create, :edit, :update, :destroy]
  	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord

	belongs_to :leader, :class_name => 'User'
	belongs_to :follower, :class_name => 'User'


end

app/models/like.rb
class Like < ApplicationRecord

	belongs_to :user
	belongs_to :tweet

end

app/models/reply.rb
class Reply < ApplicationRecord

	belongs_to :user
	belongs_to :tweet

	validates(:post, presence: true)


end

app/models/tweet.rb
class Tweet < ApplicationRecord

	has_many :replies, dependent: :destroy
	has_many :likes, dependent: :destroy
	belongs_to :user

	validates(:post, presence: true)


end

app/models/user.rb
class User < ApplicationRecord

	mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :replies
  has_many :tweets

  has_many :leaders, :class_name => 'Following', :foreign_key => 'follower_id'
  has_many :followers, :class_name => 'Following', :foreign_key => 'leader_id'

  validates(:username, :dob, :gender, presence: true)

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

   before_action :authenticate_user!
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController

	def create
		@user = User.find(params[:user_id])
		@followin = Following.new
		@followin.follower_id = current_user.id
		@followin.leader_id = @user.id
		@followin.save
		redirect_to tweets_path
	end

	def destroy
		@followin = Following.find(params[:id])
		@followin.destroy
		redirect_to tweets_path
	end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
		@twee = Tweet.find(params[:tweet_id])
		@lik = Like.new
		@lik.user_id = current_user.id
		@lik.tweet_id = @twee.id

		if @lik.save
			# redirect_to tweets_path
			respond_to do |format|
			    format.html { redirect_to tweets_path }
			    format.js { render :likeunlikebutton }
  			end
		end
	end

	def destroy
		@twee = Tweet.find(params[:tweet_id])
		@lik = Like.find(params[:id])
		if @lik.destroy
			respond_to do |format|
			    format.js { render :likeunlikebutton }
  			end
		end
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def follower
		@allprofile = User.all
		@user = current_user
	end	

	def leader
		@allprofile = User.all
		@user = current_user
	end

	def alluser
		@allprofile = User.all

	end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:avatar, :username, :dob, :gender, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:avatar, :username, :dob, :gender, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

	def create
		@twee = Tweet.find(params[:tweet_id])
		repli_params = params.require(:reply).permit(:post)
		@repli = @twee.replies.build(repli_params)
		@repli.user_id = current_user.id
		@repli.tweet_id = @twee.id
		if @repli.save
			flash[:notice] = "Replied Successfully"
			redirect_to tweet_path(id: @twee.id)
		else
			flash.now[:notice] = "Unsuccessful, please check your input"
			@twee = Tweet.find(params[:tweet_id])
			render 'tweets/show'
		end
	end

	def edit
		@twee = Tweet.find(params[:tweet_id])
		@repli = Reply.find(params[:id])
	end

	def update
		@twee = Tweet.find(params[:tweet_id])
		@repli = Reply.find(params[:id])
		repli_params = params.require(:reply).permit(:post)
		if @repli.update(repli_params)
			flash[:notice] = "Reply Updated Successfully"
			redirect_to tweet_path(id: @twee.id)
		else
			flash.now[:notice] = "Unsuccessful Reply Edit, please check your input"
			render :edit
		end
	end

	def destroy
		@twee = Tweet.find(params[:tweet_id])
		@repli = Reply.find(params[:id])
		if @repli.destroy
			flash[:notice] = "Successfully Destroyed"
			redirect_to tweet_path(id: @twee.id)
		end
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  	# before_action :find_tweet, only: [:edit, :show, :update, :destroy]

  	def find_tweet
		@twee = Tweet.find(params[:id])
  	end

	def index
		@user = current_user
		@newtwee = Tweet.new
		@twee = Tweet.all
		@lik = Like.all
		@user = current_user
		@lid = (@user.leaders.pluck(:leader_id) << @user.id)
		@leadertweet = Tweet.where(user_id: @lid)

		@tweecount = @user.tweets.count
		@leadercount = @user.leaders.count
		@followercount = @user.followers.count
		@allprofile = User.all
		@newtofollow = @allprofile.where.not(id: @user.id)

		@lik = Like.all
		@culikedtweets = @lik.where(user_id: current_user.id).pluck(:tweet_id)
		@userswholikedthesametweets = @lik.where(tweet_id: @culikedtweets).pluck(:user_id)
		@tweetsrec = Tweet.where(user_id: @userswholikedthesametweets)

		@followers = Following.where(follower_id: current_user.id)
		@leaders = @followers.pluck(:leader_id)
		@tweetsfollowrec = Tweet.where(user_id: @leaders)


		# @tweelike = Tweet.find(params[:id])
		# @likebutton = Like.find_by(user_id: current_user.id, tweet_id: @twee.id)
		# @likcount = Like.where(tweet_id: @twee.id).count
	end

	def new
		@twee = Tweet.new
	end

	def create
		# post_params = params[:tweet].permit(:post)
		@twee = Tweet.new(post_params)
		@twee.user_id = current_user.id
		
		if @twee.save
			flash[:success] = "Tweet successfully created"
			respond_to do |format|
					format.html {
			redirect_to tweets_path }
			format.js { render :tweet }
			end
		else
			flash.now[:notice] = "Tweet not successfully created"
			render "new"
		end
	end

	def show
		@twee = Tweet.find(params[:id])
		@repli = Reply.new
		
		@lik = Like.find_by(user_id: current_user.id, tweet_id: @twee.id)
		@likcount = Like.where(tweet_id: @twee.id).count
	end

	def edit
		@twee = Tweet.find(params[:id])
	end

	def update
		# post_params = params.require(:tweet).permit(:post)
		@twee = Tweet.find(params[:id])
		if @twee.update(post_params)
			flash[:notice] = "Tweet successfully updated"
			redirect_to tweets_path
		else
			flash.now[:notice] = "Tweet not successfully updated"
			render "edit"
		end

	end

	def destroy
		@twee = Tweet.find(params[:id])
		if @twee.destroy
			flash[:notice] = "Tweet successfully destroyed"
			redirect_to tweets_path
		else
			flash.now[:notice] = "Tweet not successfully destroyed"
			redirect_to tweets_path
		end
	end

	private
	def post_params
		params.require(:tweet).permit(:post)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show

		@user = User.find(params[:id])
		@leadercount = @user.leaders.count
		@followercount = @user.followers.count
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/profiles/alluser.html.erb
<h2> Find Other Tweeters! </h2>

<div class = "container">
	<div class = "row">
<!-- 	<div class = "col-sm-offset-4 col-sm-4"> -->
		<% @allprofile.each do |alluser| %>
			<div class = "col-sm-offset-1 col-sm-4">
				<div class="row">
					<div class="panel panel-danger">
						<div class="panel-body">
<!-- 	 					 	render "profiles/alluserajax", alluser: alluser -->
							<div class="user-pic">
								<%= image_tag alluser.avatar, :size => "200x150"%>
							</div>
							<div class="user-details">
								<div class = "username row">
									<b><%= alluser.username %></b>
								</div>
								</br>
								</br>
								<div class = "leaders_followers row">
										<div class="col-sm-4">
											<p>@Tweets</p>
										</div>
										<div class="col-sm-4">
											<p>@Leaders</p>
										</div>
										<div class="col-sm-4">
											<p>@Followers</p>
										</div>

										<div class="col-sm-4 text-center">
											<p><%= alluser.tweets.count %></p>
										</div>
										<div class="col-sm-4 text-center">
											<p><%= alluser.leaders.count %></p>
										</div>
										<div class="col-sm-4 text-center">
											<p><%= alluser.followers.count %></p>
										</div>
								</div>
							</div>
						</div>

						<div class="panel-footer users_buttons">
							<%= link_to "View", user_path(id: alluser.id), class:"btn btn-info" %>
							<% if @followin = Following.find_by(leader_id: alluser.id, follower_id: current_user.id) %>
								<%= link_to "Unfollow Me", user_following_path(user_id: alluser.id, id: @followin.id), method: :delete, class:"btn btn-danger", remote: true%>

							<% else %>
								<%= link_to "Follow Me", user_followings_path(user_id: alluser.id), method: :post, class:"btn btn-success", remote: true%>
							<% end %>
							<%= link_to "Back", tweets_path, class:"btn btn-primary" %>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/profiles/follower.html.erb
<h2> All Your Followers </h2>

  <% @user.followers.each do |followers| %>


  	
    <p><%= image_tag followers.follower.avatar, :size => "50x50" %> </p>

    <p><%= link_to followers.follower.username, user_path(followers.follower.id) %> </p>

	<span class="users_buttons">
		<%= link_to "View", user_path(id: followers.follower.id), class:"btn btn-info" %>
		<% if @followin = Following.find_by(leader_id: followers.follower.id, follower_id: current_user.id) %>
		<% end %>
	</div>

  <% end %>

<%= link_to "Back", tweets_path, class:"btn btn-primary" %>

app/views/profiles/leader.html.erb
<h2> All Your Leaders </h2>

<% @user.leaders.each do |leaders| %>

<p><%= image_tag leaders.follower.avatar, :size => "50x50" %> </p>

    <p><%= link_to leaders.follower.username, user_path(leaders.follower.id) %> </p>

	<span class="users_buttons">
		<%= link_to "View", user_path(id: leaders.follower.id), class:"btn btn-info" %>
		<% if @followin = Following.find_by(leader_id: leaders.follower.id, follower_id: current_user.id) %>
		<% end %>
	</div>

<% end %>

<%= link_to "Back", tweets_path %>

app/views/profiles/show.html.erb
<h2> Profile </h2>

<table class="table table-hover">
			<thead>
				<th>User</th>
				<th>Post</th>
				<th>Created At</th>
				<th>Following</th>
				<th>Followed By</th>
			</thead>
			
			<tbody>



	<% @userprofile.tweets.each do |twee| %>

					<tr>
						<td><%= twee.user.username %></td>
						<td><%= twee.post %></td>
						<td><%= distance_of_time_in_words(Time.now, twee.updated_at.localtime) %></td>
						<td><%= link_to @leadercount, tweets_path %></td>
						<td><%= link_to @followercount, follower_path %></td>
					</tr>
	<% end %>
				</tbody>
</table>

<div><%= link_to "Back", tweets_path, class:"btn btn-primary" %></div>

app/views/replies/_newreply.html.erb
				<div class="row">
					<div class="panel panel-info">
			  			<div class="panel-heading">
                        	<h3 class = "panel-title">REPLY FORM</h3>
			  			</div>
			  			<%= form_for @repli, url: tweet_replies_path(tweet_id: @twee.id), method: :post, class:"form-horizontal" do |f| %>
			  			<div class="panel-body">
							
    						<%= f.hidden_field :tweet_id %>

							<div class ="form-group row">
    							<%= f.label :reply, class:"col-sm-2 control-label" %>
    							<div class="col-sm-10">
    								<%= f.text_area :post, class:"form-control"%>
    							</div>
							</div>
						</div>
			  			<div class="panel-footer">						
							<div class="form-group row">
    							<div class="col-sm-offset-2 col-sm-10">
									<%= f.submit 'Reply', class:"btn btn-success" %>
									<%= link_to 'Back', '#', id: "BackButtonFromNewReplyForm", class:"btn btn-warning" %>
								<!-- 	<button class="btn btn-warning" id="HideReplyButton">Back
									</button> -->
								</div>
							</div>
						</div>
						<% end %>
					</div>
				</div>

app/views/replies/edit.html.erb
<h1>My Tweet and a list of replies</h1>

<div class = "container">
    <div class = "row">
<!--        <div class = "col-sm-offset-4 col-sm-4"> -->
        <div class = "col-sm-4">
            
            <div class="row">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <%= image_tag @twee.user.avatar, :size => "50x50"%>
                        Tweet by <%= @twee.user.username %>
                    </div>
                    <div class="panel-body">
                        <%= @twee.post %>
                    </div>
                    <div class="panel-footer">
                        <%= Like %>
                    </div>
                </div>
            </div>

        <% @twee.replies.each do |reply| %>
            <div class="row">
                <div class="panel panel-danger">
                    <div class="panel-heading">
                        <%= image_tag reply.user.avatar, :size => "50x50"%>
                        Replied by <%= reply.user.username %>
                    </div>
                    <div class="panel-body">
                            <%= reply.post %>
                            <%= distance_of_time_in_words(Time.now, reply.updated_at.localtime) %>
                        <div> LIKE </div>
                    </div>
                    <div class="panel-footer">
                        <%= link_to "Back", tweet_path(id: @twee.id), class:"btn btn-warning"%>      
                    </div>
                </div>
            </div>
        <% end %>


        </div>

        <div class = "col-sm-offset-1 col-sm-4">
            <div class="row">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class = "panel-title">EDIT REPLY FORM</h3>
                    </div>
                        <%= form_for @repli, url: tweet_reply_path(tweet_id: @twee.id, id: @repli.id), method: :put do |f| %>
                        <div class="panel-body">

                            <%= f.hidden_field :tweet_id %>

                            <div class ="form-group row">
                                <%= f.label :reply, class:"col-sm-2 control-label" %>
                                <div class="col-sm-10">
                                        <%= f.text_area :post, class:"form-control"%>
                                </div>
                            </div>

                        </div>

                        <div class="panel-footer">                      
                            <div class="form-group row">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <%= f.submit 'Update', class:"btn btn-info"%>
                                    <% end %>
                                    <%= link_to "Back", tweet_path(id: @twee.id), class:"btn btn-warning"%>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>


    </div>
</div>

			

app/views/tweets/_likeajax.html.erb
<% @lik = Like.find_by(user_id: current_user.id, tweet_id: twee.id) %>
<% @userid = Tweet.find(twee.id).likes.pluck(:user_id) %>
<% @userswholiked = User.where(id: @userid) %>
<% @userswholiked.each do |h| %>  

                      
  <% if @lik == nil %>

  

      <button type="button" class="btn btn-default" aria-label="Left Align", data-toggle="tooltip" data-placement="top" title=<%= h.username %>>
      <%= link_to tweet_likes_path(tweet_id: twee.id), method: :post, remote: true do %>
        <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
        <%= twee.likes.count %>
      <% end %>
      </button>
    
  <% else %>
    
      <button type="button" class="btn btn-default" aria-label="Left Align", data-toggle="tooltip" data-placement="top" title=<%= h.username %>>
      <%= link_to tweet_like_path(tweet_id: twee.id, id: @lik.id), method: :delete, remote: true do %>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <%= twee.likes.count %>
      <% end %>
    <% end %>
      </button>

  <% end %>

app/views/tweets/index.html.erb
<div class="twittertime"><h2>It's Twitter Time!</h2></div>
<div class="container-fluid indexfull">
    <div class="row">
        <div class="col-sm-3 indexprofilecol">
        	<center>
            <div class="indexprofilebluecol">
            	<div class="profileimage">
            		<%= image_tag @user.avatar, :size => "100x100"%>
            	</div>
            </div>
            </center>
            <div class="indexprofilewhitecol">
                <p class="indexprofilewhitenamecol"><b>@<%= @user.username %></b></p>
                <p class="indexprofilewhiteusernamecol"><small><code><%= @user.email %></code></small></p>
            </div>
            <table class="table table-hover indexprofiletext">
                <thead>
                    <th>
                        <p class="indexprofilewhitetextcol"><i>Tweets</i></p>
                    </th>
                    <th>
                        <p class="indexprofilewhitetextcol"><i>Following</i></p>
                    </th>
                    <th>
                        <p class="indexprofilewhitetextcol"><i>Followers</i></p>
                    </th>
                </thead>
                <tbody>
                    <tr class="indexprofilewhitetextnum">
                        <td>
                            <%= link_to @tweecount, user_path(id: current_user.id) %>
                        </td>
                        <td>
                            <%= link_to @leadercount, leader_path %>
                        </td>
                        <td>
                            <%= link_to @followercount, follower_path %>
                        </td>
                    </tr>
                </tbody>
            </table>
	            <div>
                <center>
		        <%= link_to "New Tweet", new_tweet_path, class:"btn btn-primary", id:"newtweet" %>
		            <%= link_to "Explore", alluser_path, class:"btn btn-success"%>
                </center>
		        </div>
        </div>

        <div class="col-sm-6 tweetcol">

          <div class="panel panel-default post-panel">
            <div class="panel-body row newtweet">
              <div class="col-sm-12">
                <%= form_for @newtwee, url: tweets_path, method: :post, class:'form-horizontal' do |f| %>
                    <div class="form-group row">

                        <div class="col-sm-10 newtweetbody">
                          <%= f.text_area :post, class: "form-control", rows:"2", placeholder: "My Tweet for the Day . . ." %>
                        </div>
                        <center><div class="createtweet">
                          <%= f.submit "Create", class: "btn btn-info" %>
                        </div></center>
                    </div>
                <% end %>
              </div>
            </div>
          </div>

            <% @leadertweet.order(created_at: :desc).each do |twee| %>
              <div class="panel panel-default post-panel">

                <div class="panel-body row tweetfullbody">
                  <div class="col-sm-2 tweetprofilepic">
                    <%= image_tag twee.user.avatar, :size => "50x50"%>
                  </div>
                  <div class="col-sm-10 tweettext">

                    <%= "@#{twee.user.username}" %>
                    <%= distance_of_time_in_words(Time.now, twee.updated_at.localtime) %>
                    <p>
                        <%= twee.post %>
                    </p>
                    <p data-turbolinks="false">
                      <button type="button" class="btn btn-default" aria-label="Left Align">
                      <%= link_to tweet_path(id: twee.id) do %>
                        <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
                      <%= twee.replies.count %>
                      <% end %>
                      </button>
                      <button type="button" class="btn btn-default" aria-label="Left Align">
                      <%= link_to edit_tweet_path(id: twee.id) do %>
                        <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span> Edit
                      <% end %>
                      </button>
                      <button type="button" class="btn btn-default" aria-label="Left Align">
                      <%= link_to tweet_path(id: twee.id), method: :delete do %>
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                      <% end %>
                      </button>
                      
                      <span id="likeajax-<%= twee.id %>">

                        <%= render 'tweets/likeajax', twee: twee %>

                      </span>

                    </p>
              	  </div>
                </div>
              </div>
            <% end %>
        </div>
        
        <div class="col-sm-3 allusercol">

  				<h4 class="card-title"><center> Find Other Tweeters! </center></h4>
  				
  				<div class="flex-row">
                      <% @newtofollow.each do |alluser| %>

                        <div class="panel panel-default post-panel2">

                          <div class="panel-body row findothertweeters text-center">
                            <a class="card-link"><center>
                              <%= link_to alluser.username, user_path(id: alluser.id) %>
                            </a></center>
                              <% leadercount = alluser.leaders.count %>
                              <% followercount = alluser.followers.count %>

                              <% if @followin = Following.find_by(leader_id: alluser.id, follower_id: current_user.id) %>

                                <center><span class="glyphicon glyphicon-plane" aria-hidden="true"> <%= link_to leadercount, leader_path %></span></center>

                                <center><span class="glyphicon glyphicon-user" aria-hidden="true"> <%= link_to followercount, follower_path %></span></center>

              						      <%= link_to user_following_path(user_id: alluser.id, id: @followin.id), method: :delete do %>
                                  <button type="button" class="btn btn-default unfollowmebutton" aria-label="Left Align">    
                                    <small>Unfollow me</small></button>
                                <% end %>
              					       <% else %>
                                <center><span class="glyphicon glyphicon-plane" aria-hidden="true"> <%= link_to leadercount, leader_path %></span></center>

                                <center><span class="glyphicon glyphicon-user" aria-hidden="true"> <%= link_to followercount, follower_path %></span></center>

                                <%= link_to user_followings_path(user_id: alluser.id), method: :post do %>
                                  <button type="button" class="btn btn-default" aria-label="Left Align">
                						        <small>Follow Me</small>
                                  </button>
              					         <% end %>
                              <% end %>

                          </div>
                        </div>
                      <% end %>

  				</div>
		    </div>	
	 </div>
</div>
      <div class="row">
        <div class="col-sm-6 recommendedtweets">
				  <center><h4>Tweets of Users that like the same posts as you</h4></center>
            <% @tweetsrec.order(created_at: :desc).each do |twee| %>
                <div class="panel panel-default post-panel">

                  <div class="panel-body row tweetfullbody">
                    <div class="col-sm-3 tweetprofilepic">
                      <%= image_tag twee.user.avatar, :size => "35x35"%>
                    </div>
                    <div class="col-sm-9 tweettext">

                      <%= "@#{twee.user.username}" %>
                      <%= distance_of_time_in_words(Time.now, twee.updated_at.localtime) %>
                      <p>
                          <%= twee.post %>
                      </p>
                    </div>
                  </div>
                </div>
            <% end %>
        </div>

        <div class="col-sm-6 recommendedtweets">
          <center><h4>Tweets of Users you follow</h4></center>
            <% @tweetsfollowrec.order(created_at: :desc).each do |twee| %>
                <div class="panel panel-default post-panel">

                  <div class="panel-body row tweetfullbody">
                    <div class="col-sm-3 tweetprofilepic">
                      <%= image_tag twee.user.avatar, :size => "35x35"%>
                    </div>
                    <div class="col-sm-9 tweettext">

                      <%= "@#{twee.user.username}" %>
                      <%= distance_of_time_in_words(Time.now, twee.updated_at.localtime) %>
                      <p>
                          <%= twee.post %>
                      </p>
                    </div>
                  </div>
                </div>
            <% end %>
        </div>
      </div>


    <hr>
    <div class="container">
        <div class="row">
            <div class="col-sm-offset-2 col-sm-7">
                <div class="h2newtweet">
                    <center><h3> Start A New Tweet Here </h3></center></div>
                <br>
                <%= form_for @newtwee, url: tweets_path, method: :post, class:'form-horizontal' do |f| %>
                    <div class="form-group row">
                        <%= f.label :tweet, class: "col-sm-2 control-label" %>
                            <div class="col-sm-10">
                                <%= f.text_area :post, class: "form-control", rows:"3", placeholder: "My Tweet for the Day . . ." %>
                            </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-offset-2 col-sm-10">
                            <%= f.submit "Create", class: "btn btn-info" %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>

app/views/tweets/show.html.erb
<!-- image_tag current_user.avatar, :size => "260x180"

image_tag current_user.avatar.thumb -->


<h1>My Tweet and a list of replies</h1>

<div class = "container">
	<div class = "row">
<!-- 		<div class = "col-sm-offset-4 col-sm-4"> -->
			<div class = "col-sm-4">
			
			<div class="row" id = "TweetShow" >
				<div class="panel panel-primary">
		  			<div class="panel-heading">
	  					<div class='tweeter-pic'>
		  					<%= image_tag @twee.user.avatar %>
					  	</div>
	  					<div class='tweeter-details'>
					  		<p>Tweet by <%= @twee.user.username %></p>
					  		<p><%= @twee.user.email %></p>
					  	</div>
		  			</div>
		  			<div class="panel-body">
		    			<%= @twee.post %>
		  			</div>
		  			<div class="panel-footer">
		  				
						<button class="btn btn-success" id="ReplyButtonFromTweetShow">Reply
							</button>
						<%= link_to tweets_path, class:"btn btn-warning" do %><span class="glyphicon glyphicon-circle-arrow-left"></span>Back


		  				<% if @twee.user.id == current_user.id %>

							<!--link_to creates <a> which will redirect, so what happens after the jquery on will restart over -->	
		  					<button class="btn btn-primary" id="EditButtonFromTweetShow">
		  						<span class="glyphicon glyphicon-pencil"></span> Edit
		  					</button>	

							<span class = "badge glyphicon glyphicon-heart"><%= @likcount %></span>

							
							<% end %>



						<% end %>
		  			</div>
				</div>
			</div>

			<div class="row" id = "EditTweetForm" >
				<%= render "tweets/edit" %>
			</div>

			<% @twee.replies.each do |reply| %>
				<div class="row">
					<div class="panel panel-danger">
			  			<div class="panel-heading">
			  				<div class = "reply-pic">
			  					<%= image_tag reply.user.avatar%>
			  				</div>
			  				<div class = "reply-details">
			  					<p>Replied by <%= reply.user.username %></p>
			  					<p><%= reply.user.email %></p>
						  	</div>
			  			</div>
			  			<div class="panel-body">
			    			<%= reply.post %>
			    			<%= distance_of_time_in_words(Time.now, reply.updated_at.localtime) %>
			    			<div> LIKE </div>
			  			</div>
			  			<div class="panel-footer">
							<%= link_to edit_tweet_reply_path(tweet_id: @twee.id, id: reply.id), class:"btn btn-primary" do %><span class="glyphicon glyphicon-pencil"></span> Edit 
							<% end %>		
							<%= link_to tweet_reply_path(tweet_id: @twee.id, id: reply.id), method: :delete, class:"btn btn-warning" do %><span class="glyphicon glyphicon-trash"></span> Delete
							<% end %>
			  			</div>
	 				</div>
				</div>
			<% end %>

		</div>

		<div class = "col-sm-offset-1 col-sm-4" id = "NewTweetForm">
			<%= render "replies/newreply" %>
		</div>

	</div>	
</div>